(()=>{
'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const API='https://jkmrjeplpsfpciveycia.supabase.co/functions/v1/campus-dash-api';
const C=$('#gameCanvas'),X=C.getContext('2d'),W=$('#canvasWrap');
const CH=[
{id:'fred',name:'Freshman Fred',emoji:'🎒',cost:0,shirt:'#4f7df3',skin:'#e0ad82',desc:'New campus. Wrong building. Still running.'},
{id:'chloe',name:'Caffeine Chloe',emoji:'☕',cost:250,shirt:'#d75979',skin:'#b77b55',desc:'Powered by espresso and questionable decisions.'},
{id:'liam',name:'Late-to-Class Liam',emoji:'⏰',cost:500,shirt:'#33a97b',skin:'#d8a078',desc:'Has never once left home on time.'},
{id:'sam',name:'Scholarship Sam',emoji:'📚',cost:800,shirt:'#7b61d8',skin:'#855a42',desc:'Runs like the GPA depends on it.'},
{id:'sid',name:'Senioritis Sid',emoji:'😴',cost:1200,shirt:'#e28a2e',skin:'#efc292',desc:'One semester from freedom. Allegedly.'},
{id:'pat',name:'Parking Pat',emoji:'🎫',cost:2000,shirt:'#d84b45',skin:'#c88b67',desc:'Left the citation cart to chase you personally.'},
{id:'dean',name:'The Dean',emoji:'🎓',cost:3500,shirt:'#20233c',skin:'#d8a078',desc:'Full academic robes. Maximum administrative speed.'}];
const EV=[['CAMPUS QUAD','#74c8ef','#70b95f','#6b6f78'],['PARKING LOT PANIC','#8ac9e7','#767a84','#474b55'],['DORM DISASTER','#d39469','#8b5d48','#5f5150'],['LIBRARY RUSH','#25334f','#6a4a35','#49454b'],['STUDENT CENTER','#73c7dd','#c08a59','#65666e'],['FINALS WEEK','#68548f','#43375f','#514c62'],['GRADUATION DAY','#65c7ef','#6dbc68','#575b65']];
const OB=[['🎒','jump'],['🚲','jump'],['⚠️','avoid'],['🛒','avoid'],['📱','avoid'],['🚧','jump'],['↕️','slide'],['📋','slide']];
const PW=[['coffee','COFFEE RUSH','☕',5000],['magnet','EXTRA CREDIT MAGNET','🧲',8000],['shield','GRAD CAP SHIELD','🎓',0],['pass',"PROFESSOR'S PASS",'🪪',6000],['slow','ALL-NIGHTER','🌙',5000],['guide','STUDY GUIDE','📝',7000],['double','DOUBLE CREDITS','✌️',8000]];
const QU=['You know attendance is 20% of your grade, right?','Interesting strategy: arriving after class ends.','The syllabus did, in fact, mention the start time.','Your alarm clock would like a word.','You were so close. To the wrong building.','Office hours are not a substitute for showing up.'];
const EVENTS=[['FIRE DRILL','Everybody exits at once. Of course.'],['FREE PIZZA','Suddenly everyone knows where the student center is.'],['MIDTERM WEEK','The papers are flying and so are you.'],['CAMPUS TOUR','Matching parent lanyards ahead.'],['PARKING ENFORCEMENT','Parking Pat has entered the chat.']];
const MISS=[['jumps','Jump over {n} obstacles',8],['credits','Collect {n} Campus Credits',35],['distance','Run {n} meters',700],['close','Get {n} close calls',4],['slides','Slide under {n} obstacles',5],['maxMult','Reach a x{n} multiplier',4]];
let set=read('cd_settings',{sound:true,shake:true,motion:false,touch:true}),p=read('cd_save',null)||fresh(),g=null,raf=0,last=0,audio=null,pending='endless',board='endless',down=null;
function read(k,f){try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}function uid(){return crypto.randomUUID?crypto.randomUUID():'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,c=>{let r=Math.random()*16|0;return(c==='x'?r:r&3|8).toString(16)})}function fresh(){return{save_token:uid(),nickname:'',high_score:0,longest_distance:0,campus_credits:0,level:1,xp:0,characters_unlocked:['fred'],cosmetics_unlocked:[],missions_completed:0,best_time_attack:0,best_daily:0,selected_character:'fred',runs:0}}function clean(v){return String(v||'').trim().replace(/[^a-zA-Z0-9 _-]/g,'').replace(/\s+/g,' ').slice(0,18)}function cl(n,a,b){return Math.max(a,Math.min(b,n))}function char(){return CH.find(x=>x.id===p.selected_character)||CH[0]}function today(){return new Date().toISOString().slice(0,10)}function hash(s){let h=2166136261;for(const c of s){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}function rng(a){return()=>{a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}
function show(id){$$('.screen').forEach(e=>e.classList.remove('active'));$('#'+id).classList.add('active');if(id!=='game'){cancelAnimationFrame(raf);raf=0}}function menu(){localStorage.setItem('cd_save',JSON.stringify(p));$('#saveStatus').textContent=`${p.nickname||'No runner saved'} • Level ${p.level} • ${p.campus_credits.toLocaleString()} Campus Credits`;$('#posterBest').textContent=Number(p.high_score||0).toLocaleString()}function saveSet(){localStorage.setItem('cd_settings',JSON.stringify(set));$('#soundSetting').checked=set.sound;$('#shakeSetting').checked=set.shake;$('#motionSetting').checked=set.motion;$('#touchSetting').checked=set.touch;$('#soundToggle').textContent=set.sound?'🔊':'🔇';document.body.classList.toggle('hideTouch',!set.touch)}function tone(k='tap'){if(!set.sound)return;try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();let o=audio.createOscillator(),v=audio.createGain(),t=audio.currentTime,f=k==='credit'?760:k==='crash'?70:k==='power'?560:k==='close'?900:360,d=k==='crash'?.32:.07;o.type=k==='crash'?'sawtooth':'square';o.frequency.value=f;v.gain.setValueAtTime(.04,t);v.gain.exponentialRampToValueAtTime(.001,t+d);o.connect(v);v.connect(audio.destination);o.start(t);o.stop(t+d)}catch{}}function shake(){if(set.shake&&!set.motion){W.classList.remove('shake');void W.offsetWidth;W.classList.add('shake')}}function note(a,b='',ms=800){let e=$('#gameOverlay');e.innerHTML=`${a}${b?`<small>${b}</small>`:''}`;e.classList.remove('hidden');clearTimeout(e._t);e._t=setTimeout(()=>{if(g&&!g.paused)e.classList.add('hidden')},ms)}
async function api(action,x={}){let r=await fetch(API,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,...x})});if(!r.ok)throw Error(await r.text());return r.json()}async function cloud(){menu();try{await api('save',{save:p})}catch(e){console.warn(e)}}async function loadCloud(){if(!p.nickname)return;try{let d=await api('load',{save_token:p.save_token});if(d.save){p={...p,...d.save};menu()}}catch(e){console.warn(e)}}async function submit(){try{await api('submit_score',{entry:{save_token:p.save_token,nickname:p.nickname,mode:g.mode,score:Math.round(g.score),distance:Math.round(g.distance),multiplier:g.maxMult,credits:g.credits,challenge_key:g.mode==='daily'?today():''}})}catch(e){console.warn(e)}}
function setup(m){pending=m;let s=$('#characterSelect');s.innerHTML='';CH.filter(x=>p.characters_unlocked.includes(x.id)).forEach(x=>s.add(new Option(x.name,x.id,x.id===p.selected_character,x.id===p.selected_character)));$('#nickname').value=p.nickname;$('#setupError').textContent='';show('setup')}function locker(){show('locker');let b=$('#characterCards');b.innerHTML='';CH.forEach(c=>{let u=p.characters_unlocked.includes(c.id),sel=p.selected_character===c.id,e=document.createElement('article');e.className='characterCard'+(sel?' selected':'');e.innerHTML=`<div class="avatar">${c.emoji}</div><h3>${c.name}</h3><p>${c.desc}</p><button class="${sel?'secondary':'primary'}"></button>`;let q=e.querySelector('button');if(sel){q.textContent='SELECTED';q.disabled=true}else if(u){q.textContent='SELECT';q.onclick=()=>{p.selected_character=c.id;menu();locker()}}else{q.textContent=`UNLOCK • ${c.cost.toLocaleString()} CREDITS`;q.disabled=p.campus_credits<c.cost;q.onclick=()=>{if(p.campus_credits<c.cost)return;p.campus_credits-=c.cost;p.characters_unlocked.push(c.id);p.selected_character=c.id;tone('power');cloud();locker()}}b.append(e)})}
function missions(seed){let r=seed?rng(seed):Math.random,a=[...MISS],o=[];while(o.length<3){let i=Math.floor(r()*a.length),m=a.splice(i,1)[0];o.push({key:m[0],label:m[1],target:m[2],done:false})}return o}function mval(m){return m.key==='credits'?g.credits:Math.floor(g[m.key]||0)}function missionUI(){for(const m of g.missions){if(!m.done&&mval(m)>=m.target){m.done=true;g.done++;g.credits+=75;g.score+=500*g.mult;p.missions_completed++;note('MISSION COMPLETE!','+75 Campus Credits',650);tone('power')}}$('#missionHud').innerHTML=g.missions.map(m=>`<div class="${m.done?'missionDone':''}">${m.done?'✓':'○'} ${m.label.replace('{n}',m.target)} <b>${Math.min(mval(m),m.target)}/${m.target}</b></div>`).join('')}
function start(mode){let seed=mode==='daily'?hash(today()):Math.random()*2**32>>>0;g={mode,r:rng(seed),lane:0,target:0,visual:0,jump:0,jv:0,slide:false,slideTo:0,paused:false,ended:false,elapsed:0,distance:0,score:0,credits:0,mult:1,maxMult:1,streak:0,speed:1,objects:[],spawn:300,env:0,eventAt:18000,stored:null,active:{},inv:0,jumps:0,slides:0,close:0,done:0,missions:missions(mode==='daily'?hash(today()+'m'):0),safe:0,time:120};$('#modeLabel').textContent=mode==='daily'?'DAILY':mode==='time_attack'?'TIME ATTACK':'ENDLESS';show('game');note(mode==='daily'?'DAILY CHALLENGE':mode==='time_attack'?'2:00 TIME ATTACK':'CLASS STARTED 2 MINUTES AGO',mode==='daily'?'Same course for everyone today.':'RUN!',1100);missionUI();hud();last=performance.now();loop(last)}function loop(t){let dt=Math.min(40,t-last);last=t;if(g&&!g.paused&&!g.ended)update(t,dt);draw(t);if($('#game').classList.contains('active'))raf=requestAnimationFrame(loop)}function active(id,t=performance.now()){return(g?.active?.[id]||0)>t}
function spawn(){let L=[-1,0,1],safe=L[Math.floor(g.r()*3)],blocks=g.r()<(.3+cl(g.distance/1600,0,.45))?2:1;g.safe=safe;L.filter(x=>x!==safe).sort(()=>g.r()-.5).slice(0,blocks).forEach(l=>{let o=OB[Math.floor(g.r()*OB.length)];g.objects.push({k:'o',lane:l,z:0,icon:o[0],need:o[1],hit:false})});let lane=g.r()<.7?safe:L[Math.floor(g.r()*3)];for(let i=0;i<4+Math.floor(g.r()*3);i++)g.objects.push({k:'c',lane,z:-i*.07,hit:false});if(g.r()<.14){let q=PW[Math.floor(g.r()*PW.length)];g.objects.push({k:'p',lane:safe,z:-.12,power:q[0],icon:q[2],hit:false})}}
function update(t,dt){g.elapsed+=dt;g.speed=Math.min(1.75,1+g.elapsed/100000*.62)*(active('coffee',t)?1.12:1);let wf=active('slow',t)?.65:1,d=dt*.012*g.speed;g.distance+=d;g.score+=d*3*g.mult;if(g.mode==='time_attack'){g.time=Math.max(0,120-g.elapsed/1000);if(g.time<=0)return finish('TIME!')}let env=Math.floor(g.distance/430)%7;if(env!==g.env){g.env=env;note(EV[env][0],env===5?'You may begin panicking.':'',700)}if(g.elapsed>g.eventAt){let e=EVENTS[Math.floor(g.r()*EVENTS.length)];note(e[0],e[1],900);g.eventAt=g.elapsed+22000+g.r()*15000}g.visual+=(g.target-g.visual)*Math.min(1,dt*.014);if(g.jump>0||g.jv>0){g.jv-=dt*.0025;g.jump+=g.jv*dt;if(g.jump<0){g.jump=0;g.jv=0}}if(g.slide&&t>g.slideTo)g.slide=false;g.spawn-=dt*wf;if(g.spawn<=0){spawn();g.spawn=(760+g.r()*480)/g.speed}for(const o of g.objects){o.z+=dt*.00022*g.speed*wf;if(!o.hit&&o.z>.83)check(o,t)}g.objects=g.objects.filter(o=>o.z<1.18);missionUI();hud()}
function check(o,t){o.hit=true;let same=Math.abs(o.lane-g.visual)<.42;if(o.k==='c'){if(same||active('magnet',t)){let n=active('double',t)?2:1;g.credits+=n;g.score+=35*n*g.mult;g.streak++;if(g.streak%18===0){g.mult=Math.min(5,g.mult+1);g.maxMult=Math.max(g.maxMult,g.mult);note(`x${g.mult} MULTIPLIER!`,'Keep the streak alive.',450)}tone('credit');o.z=2}else g.streak=0;return}if(o.k==='p'){if(same){g.stored=o.power;note('POWER-UP!',PW.find(x=>x[0]===o.power)[1],500);tone('power');o.z=2}return}if(!same)return;let safe=active('coffee',t)||active('pass',t)||t<g.inv||(o.need==='jump'&&g.jump>42)||(o.need==='slide'&&g.slide);if(safe){if(o.need==='jump')g.jumps++;if(o.need==='slide')g.slides++;g.close++;g.score+=220*g.mult;if(g.close%3===0){g.mult=Math.min(5,g.mult+1);g.maxMult=Math.max(g.maxMult,g.mult)}note('CLOSE CALL!',`x${g.mult} multiplier`,360);tone('close');return}if(active('shield',t)){delete g.active.shield;note('SHIELD SAVED YOU!','Graduation remains technically possible.',600);shake();return}crash()}
function crash(){tone('crash');shake();g.mult=1;g.streak=0;if(g.mode==='time_attack'){g.score=Math.max(0,g.score-750);g.inv=performance.now()+1500;note('OUCH!','-750 points • keep running',700)}else finish('CRASH')}
function move(n){if(!g||g.paused||g.ended)return;g.target=cl(g.target+n,-1,1)}function jump(){if(!g||g.paused||g.ended||g.jump>1)return;g.jv=.72;g.slide=false;tone()}function slide(){if(!g||g.paused||g.ended||g.jump>20)return;g.slide=true;g.slideTo=performance.now()+680}function power(){if(!g||!g.stored||g.paused)return;let q=PW.find(x=>x[0]===g.stored),now=performance.now();g.active[q[0]]=q[0]==='shield'?Number.MAX_SAFE_INTEGER:now+q[3];g.stored=null;note(q[1],'ACTIVATED!',550);tone('power')}function pause(){if(!g||g.ended)return;g.paused=!g.paused;$('#pauseBtn').textContent=g.paused?'RESUME':'PAUSE';if(g.paused){let e=$('#gameOverlay');e.innerHTML='PAUSED<small>Press P or Resume</small>';e.classList.remove('hidden')}else $('#gameOverlay').classList.add('hidden')}
function hud(){if(!g)return;$('#scoreText').textContent=Math.round(g.score).toLocaleString();$('#distanceText').textContent=Math.round(g.distance)+'m';$('#multText').textContent='x'+g.mult;$('#creditsText').textContent=g.credits;let sec=g.mode==='time_attack'?Math.ceil(g.time):Math.floor(g.elapsed/1000);$('#timeText').textContent=Math.floor(sec/60)+':'+String(sec%60).padStart(2,'0');let q=PW.find(x=>x[0]===g.stored);$('#powerHud').innerHTML=q?`STORED: ${q[2]} ${q[1]}<br><small>Press E</small>`:'NO POWER STORED'}
async function finish(reason){if(!g||g.ended)return;g.ended=true;let score=Math.round(g.score),dist=Math.round(g.distance),newHigh=g.mode==='endless'&&score>(p.high_score||0);if(g.mode==='endless')p.high_score=Math.max(p.high_score||0,score);if(g.mode==='time_attack')p.best_time_attack=Math.max(p.best_time_attack||0,score);if(g.mode==='daily')p.best_daily=Math.max(p.best_daily||0,score);p.longest_distance=Math.max(p.longest_distance||0,dist);p.campus_credits+=g.credits;p.xp+=Math.round(dist/5)+g.done*100;p.level=Math.floor(p.xp/1000)+1;p.runs++;await cloud();await submit();show('gameOver');$('#resultEyebrow').textContent=newHigh?'NEW HIGH SCORE!':reason==='TIME!'?'TIME ATTACK COMPLETE':'RUN OVER';$('#resultTitle').textContent=reason==='TIME!'?'BELL RANG.':"YOU'RE LATE.";$('#professorQuote').textContent='“'+QU[Math.floor(Math.random()*QU.length)]+'”';$('#runStats').innerHTML=`<div><small>SCORE</small><b>${score.toLocaleString()}</b></div><div><small>DISTANCE</small><b>${dist}m</b></div><div><small>CREDITS</small><b>+${g.credits}</b></div><div><small>BEST MULTIPLIER</small><b>x${g.maxMult}</b></div><div><small>CLOSE CALLS</small><b>${g.close}</b></div><div><small>MISSIONS</small><b>${g.done}/3</b></div>`;$('#resultStatus').textContent='Run saved. Best scores can appear online.'}
function pt(l,z){let h=75+Math.pow(cl(z,0,1),1.18)*385;return{x:480+l*h*.56,y:112+Math.pow(cl(z,0,1),1.55)*365,s:.2+z}}
function bg(){let e=EV[g?.env||0];X.fillStyle=e[1];X.fillRect(0,0,960,540);X.fillStyle=e[2];X.fillRect(0,150,960,390);X.fillStyle='#101522cc';X.fillRect(0,108,960,38);X.fillStyle='#fff';X.font='900 18px system-ui';X.textAlign='center';X.fillText(e[0],480,134);if(g?.env===5){X.fillStyle='#fff9';for(let i=0;i<18;i++)X.fillRect((i*97+g.elapsed*.02)%960,75+(i*43)%220,14,8)}if(g?.env===6){for(let i=0;i<24;i++){X.fillStyle=['#ffd84f','#ff6b7a','#6ee7ff'][i%3];X.fillRect((i*67+g.elapsed*.03)%960,(i*53)%250,5,10)}}}
function road(){X.fillStyle=EV[g?.env||0][3];X.beginPath();X.moveTo(405,142);X.lineTo(555,142);X.lineTo(920,540);X.lineTo(40,540);X.closePath();X.fill();X.strokeStyle='#fff8';for(const l of[-.5,.5])for(let i=0;i<11;i++){let z=((i/11)+(g?.distance||0)*.002)%1,a=pt(l,z),b=pt(l,Math.min(1,z+.04));X.lineWidth=Math.max(1,a.s*4);X.beginPath();X.moveTo(a.x,a.y);X.lineTo(b.x,b.y);X.stroke()}}
function obj(o){if(o.z<0)return;let a=pt(o.lane,o.z);X.save();X.translate(a.x,a.y);X.scale(a.s,a.s);X.textAlign='center';if(o.k==='c'){X.fillStyle='#ffd84f';X.beginPath();X.arc(0,0,16,0,7);X.fill();X.fillStyle='#493d00';X.font='900 14px system-ui';X.fillText('C',0,5)}else{X.font=(o.k==='p'?30:40)+'px system-ui';X.fillText(o.k==='p'?o.icon:o.icon,0,10)}X.restore()}
function runner(){let c=char(),a=pt(g?g.visual:0,1),y=458-(g?.jump||0),sl=g?.slide;X.save();X.translate(a.x,y);X.scale(1.15,sl?.75:1.15);X.fillStyle='#0004';X.beginPath();X.ellipse(0,34,30,9,0,0,7);X.fill();X.strokeStyle=c.skin;X.lineWidth=11;X.lineCap='round';let q=Math.sin((g?.elapsed||0)*.018)*10;X.beginPath();X.moveTo(-8,4);X.lineTo(-18+q,32);X.moveTo(8,4);X.lineTo(18-q,32);X.stroke();X.fillStyle=c.shirt;X.fillRect(-20,-38,40,48);X.fillStyle=c.skin;X.beginPath();X.arc(0,-54,16,0,7);X.fill();X.font='19px system-ui';X.fillText(c.emoji,-9,-73);if(active('shield')){X.strokeStyle='#ffd84f';X.lineWidth=4;X.beginPath();X.arc(0,-20,52,0,7);X.stroke()}X.restore()}
function draw(){X.clearRect(0,0,960,540);bg();road();if(g)for(const o of [...g.objects].sort((a,b)=>a.z-b.z))obj(o);if(g&&active('guide')){let a=pt(g.safe,.72),b=pt(g.safe,.95);X.strokeStyle='#74f09a99';X.lineWidth=18;X.beginPath();X.moveTo(a.x,a.y);X.lineTo(b.x,b.y);X.stroke()}runner()}
async function leaderboard(m=board){board=m;show('leaderboard');$$('[data-board-mode]').forEach(b=>b.classList.toggle('active',b.dataset.boardMode===m));$('#boardStatus').textContent='Loading online leaderboard…';let b=$('#boardBody');b.innerHTML='';try{let d=await api('leaderboard',{mode:m,challenge_key:m==='daily'?today():''});$('#boardStatus').textContent=m==='daily'?`Daily Challenge • ${today()}`:'Online Top 10';if(!d.entries.length)b.innerHTML='<tr><td colspan="5">No scores yet. Be the first.</td></tr>';d.entries.forEach((r,i)=>{let tr=document.createElement('tr');tr.innerHTML=`<td>${i+1}</td><td></td><td>${Number(r.score).toLocaleString()}</td><td>${r.distance}m</td><td>x${r.multiplier}</td>`;tr.children[1].textContent=r.nickname;b.append(tr)})}catch{$('#boardStatus').textContent='Leaderboard temporarily unavailable.'}}
$('#runBtn').onclick=()=>setup('endless');$('#dailyBtn').onclick=()=>setup('daily');$('#timeBtn').onclick=()=>setup('time_attack');$('#lockerBtn').onclick=locker;$('#boardBtn').onclick=()=>leaderboard('endless');$('#howBtn').onclick=()=>show('how');$('#settingsBtn').onclick=()=>show('settings');$$('.back').forEach(b=>b.onclick=()=>show('menu'));$('#setupForm').onsubmit=e=>{e.preventDefault();let n=clean($('#nickname').value);if(n.length<2)return $('#setupError').textContent='Use a nickname with at least 2 characters.';p.nickname=n;p.selected_character=$('#characterSelect').value||'fred';cloud();start(pending)};$('#pauseBtn').onclick=pause;$('#quitBtn').onclick=()=>finish('QUIT');$('#resultMenuBtn').onclick=()=>show('menu');$('#runAgainBtn').onclick=()=>start(g?.mode||'endless');$('#soundToggle').onclick=()=>{set.sound=!set.sound;saveSet()};$('#soundSetting').onchange=e=>{set.sound=e.target.checked;saveSet()};$('#shakeSetting').onchange=e=>{set.shake=e.target.checked;saveSet()};$('#motionSetting').onchange=e=>{set.motion=e.target.checked;saveSet()};$('#touchSetting').onchange=e=>{set.touch=e.target.checked;saveSet()};$$('[data-board-mode]').forEach(b=>b.onclick=()=>leaderboard(b.dataset.boardMode));$$('[data-action]').forEach(b=>b.onpointerdown=e=>{e.preventDefault();let a=b.dataset.action;a==='left'?move(-1):a==='right'?move(1):a==='jump'?jump():a==='slide'?slide():power()});
addEventListener('keydown',e=>{if(!$('#game').classList.contains('active'))return;let k=e.key.toLowerCase();if(['arrowleft','arrowright','arrowup','arrowdown',' ','a','d','w','s','e','p'].includes(k))e.preventDefault();if(k==='arrowleft'||k==='a')move(-1);else if(k==='arrowright'||k==='d')move(1);else if(k==='arrowup'||k==='w'||k===' ')jump();else if(k==='arrowdown'||k==='s')slide();else if(k==='e')power();else if(k==='p')pause()},{passive:false});C.onpointerdown=e=>down=[e.clientX,e.clientY];C.onpointerup=e=>{if(!down)return;let dx=e.clientX-down[0],dy=e.clientY-down[1];down=null;if(Math.max(Math.abs(dx),Math.abs(dy))<25)return;Math.abs(dx)>Math.abs(dy)?move(dx>0?1:-1):dy<0?jump():slide()};
saveSet();menu();draw();loadCloud();
})();